stages:
   - output
   - build
   - deploy
output_job:
   stage: output
   script:
      - echo "$CI_PROJECT_DIR"
build react-app:  
   image: node:16.17.0
   stage: build  
   only:    
      - master  
   script:  
      # Set PATH
      - export PATH=$PATH:/usr/bin/npm
      # Change Direction 
      - cd /builds/YakovAntipenko/test/web/
      # Install dependencies    
      - npm install 
      # Build App    
      - CI=false npm run build 
   artifacts:    
      paths:      
         # Public/ folder      
         - web/public/
deploy master:
   image: python:latest
   stage: deploy
   only:
      - master
   script:
      - pip3 install awscli
      - aws s3 sync /builds/YakovAntipenko/test/web/public/ s3://$S3_BUCKET_NAME 
      - aws cloudfront create-invalidation --distribution-id $DISTR_ID --paths '/*'
