---
- name: Ping my servers
  hosts: SQL
  become: yes
  vars: 
    ansible_python_interpreter: /usr/bin/python3.10

  tasks:
  - name: pip install    
    apt: name=python3-pip state=present

  - name: Install python3.10    
    apt: name=python3.10 state=latest

  - name: Pip install Docker Module for Python
    pip: 
      name: docker 