---
 - hosts: all
   become: yes
   tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/YakovAntipenko/Lesson9.git
       dest: /home/repo
       clone: yes
       update: yes